[package]
name = "async-pipe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-lock = "2.8.0"
futures-util = "0.3.28"

[dev-dependencies]
tokio = {version = "1.32.0", features = ["full"]}
